[build]
  publish = "dist/spa"
  command = "npm run build"

[[redirects]]
  from = "/api/scan/coins"
  to = "/.netlify/functions/scan-coins"
  status = 200

[[redirects]]
  from = "/api/scan/start"
  to = "/.netlify/functions/scan-start"
  status = 200

[[redirects]]
  from = "/api/scan/status"
  to = "/.netlify/functions/scan-status"
  status = 200

[[redirects]]
  from = "/api/backup-coins"
  to = "/.netlify/functions/backup-coins"
  status = 200

[[redirects]]
  from = "/api/whale-tracking"
  to = "/.netlify/functions/whale-tracking"
  status = 200

[[redirects]]
  from = "/api/ping"
  to = "/.netlify/functions/ping"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/opt/buildhome/.local"

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  OPENAI_API_KEY = "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"
  SOLANA_RPC_URL = "https://api.mainnet-beta.solana.com"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
